# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/fic_db
spring.datasource.username=postgres
spring.datasource.password=Angie2001.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Internacionalizacion
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# API datos.gov.co
# datos.gov.app-token=2ghunn1yq56zpwr47f4fbo57fyqsj4kd7eqrg35u894yyx55zr

# Clave admin para auditoria
admin.audit-key=claveAdmin2024

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# JWT
jwt.secret=ficColombiaSecretKey2026XyZ987654321AB

# SSL / HTTPS
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:fic-keystore.p12
server.ssl.key-store-password=ficKeystore2024
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=fic-platform

# Puerto HTTP redirige a HTTPS
server.http.port=8080